### ISSUE TITLE
Add fees limit to batcher to avoid DA overcharging on blobs

### ISSUE THREAD

**Issue by dshiell** [polymerdao/optimism-dev#14]
blob pricing can spike unexpectedly so we need to add a safeguard to ensure that we don't accidentally spend a fortune on our DA updates.

**Comment by alfredo-stonk** [comment]
Related [PR](https://github.com/ethereum-optimism/optimism/pull/11219) that enables op-batcher: Add dynamic blob/calldata selection

**Comment by dshiell** [comment]
No such config exists
